/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aliyun_icon_IconGenerator */

#ifndef _Included_com_aliyun_icon_IconGenerator
#define _Included_com_aliyun_icon_IconGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aliyun_icon_IconGenerator
 * Method:    generator
 * Signature: ([I[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_aliyun_icon_IconGenerator_generator
  (JNIEnv *, jobject, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
