/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aliyun_icon_IconGenerator */

#ifndef _Included_com_aliyun_icon_ImageUtils
#define _Included_com_aliyun_icon_ImageUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aliyun_icon_IconGenerator
 * Method:    getBitmapAverageColor
 * Signature: ([I[I[I)I
 */
JNIEXPORT jlong JNICALL Java_com_aliyun_icon_IconGenerator_getBitmapAverageColor(
        JNIEnv *env, jclass cls, jobject srcBitmap, jint startX, jint startY,
        jint w, jint h, jint stepX, jint stepY);

#ifdef __cplusplus
}
#endif
#endif
